FROM php:8.2

RUN apt-get update && apt-get install -y \
    git unzip zip curl \
    && docker-php-ext-install pcntl

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
COPY . .

RUN composer install --ignore-platform-reqs

CMD php artisan reverb:start --host=0.0.0.0 --port=${PORT}